trial_name: 'bump_inter'
evaluate_training_predictions: True

features:
  input: ["Ux", "Uy", 'dUx_dx','dUx_dy', 'dUy_dy', 'dUy_dx']
  output: ['p']
  transport_feature: True
  transport_norm: 'log'        # i.e., transport scaling is disabled


paths:
  output_dir: "final_outputs"
  name: "final_bump"
  data: 'Data'

model:
  activation: 'leakyrelu'
  dropout: 0.05
  layers: 10
  type: 'FCN'
  width: 10
  seed: 42

training:
  feature_norm: 'nondim_local'
  scale_norm: 'minmax'        # applies per-case [0,1] normalization
  norm_labels: True
  lamb: 0.0001
  eval_every: 10
  epochs: 5000
  batch_size: 2048
  lr: 0.005
  loss_case_scaling:
    loss_mode: 'tke'     #modes = ['tke', 'tke_sq']
    loss_type: ''       #sum or mean
    loss_scale: ''      #max or mean of loss vector
  loss_terms:
    mse_weight: 1
    tke: True
    tke_weight: 1
  scheduler:
    enabled: True
    type: "reduce"
    step_size: [250, 0.001]      #for linear use [start_epoch, tgt_pct], for multistep do [step_1, step_2, ... step_n]
    gamma: 0.6            #these are for reduce on plateau
    factor: 0.8
    patience: 100
    min_lr: 1e-6
    cooldown: 10
    verbose: False






