trial_name: 'phill_inter'
evaluate_training_predictions: True

features:
  input: ["Ux", "Uy", 'p', 'wallDistance', 'dp_0', 'dp_1'] #,'dUx_dx', 'dUx_dy', 'dUy_dy']
  output: ['uu', 'uv', 'uw', 'vv', 'vw', 'ww']
  transport_feature: True
  transport_norm: 'log'        # i.e., transport scaling is disabled


paths:
  output_dir: "RST_outputs"
  name: "kde_minmax"
  data: 'Data'

model:
  activation: 'leakyrelu'
  dropout: 0.05
  layers: 10
  type: 'FCN'
  width: 10
  seed: 41

training:
  feature_norm: ''
  scale_norm: 'minmax'        # applies per-case [0,1] normalization
  norm_labels: False
  lamb: 0.0001
  eval_every: 10
  epochs: 10
  batch_size: 2048
  lr: 0.01
  loss_case_scaling:
    loss_mode: 'tke_sq'     #modes = ['tke', 'tke_sq']
    loss_type: ''       #sum or mean
    loss_scale: ''      #max or mean of loss vector
  loss_terms:
    mse_weight: 1
    use_phys_loss: 'True'
    tke: True
    tke_weight: 5
  scheduler:
    enabled: True
    type: 'linear'
    step_size: [250, 0.01]      #for linear use [start_epoch, tgt_pct], for multistep do [step_1, step_2, ... step_n]
    gamma: 0.6            #these are for reduce on plateau
    factor: 0.8
    patience: 100
    min_lr: 1e-6
    cooldown: 10
    verbose: False






