evaluate_training_predictions: true
features:
  input:
  - Ux
  - Uy
  - wallDistance
  - p
  - dp_0
  - dp_1
  output:
  - uu
  - uv
  - uw
  - vv
  - vw
  - ww
  transport_feature: true
  transport_norm: log
model:
  grid: 20
  grid_range:
  - -1.1
  - 1.1
  seed: 42
  shape:
  - - 7
    - 0
  - - 6
    - 6
  - - 6
    - 6
  - - 3
    - 3
  - - 6
    - 0
  spline_order: 3
  type: kan
  update_grid: true
  use_kan: true
paths:
  data: Data
  name: kan_test6
  output_dir: rst_outputs
training:
  batch_size: 2048
  epochs: 250
  eval_every: 5
  feature_norm: nondim_local
  lamb: 0.001
  loss_mode: tke
  loss_scale: max
  loss_type: mean
  lr: 0.01
  norm_labels: false
  opt: Adam
  scale_norm: minmax
  scheduler:
    enabled: true
    gamma: 0.7
    step_size:
    - 5
    - 0.001
    type: linear
  seed: 21
  use_fit: false
trial_name: full_inter
