evaluate_training_predictions: true
features:
  input:
  - Ux
  - Uy
  - p
  - wallDistance
  - dp_0
  - dp_1
  output:
  - uu
  - uv
  - uw
  - vv
  - vw
  - ww
  transport_feature: true
  transport_norm: log
model:
  activation: leakyrelu
  dropout: 0.05
  layers: 10
  seed: 41
  type: FCN
  width: 10
paths:
  data: Data
  name: kde_nondim
  output_dir: RST_outputs
training:
  batch_size: 2048
  epochs: 10
  eval_every: 10
  feature_norm: nondim_local
  lamb: 0.0001
  loss_case_scaling:
    loss_mode: tke_sq
    loss_scale: ''
    loss_type: ''
  loss_terms:
    mse_weight: 1
    tke: true
    tke_weight: 5
    use_phys_loss: 'True'
  lr: 0.01
  norm_labels: false
  scale_norm: ''
  scheduler:
    cooldown: 10
    enabled: true
    factor: 0.8
    gamma: 0.6
    min_lr: 1e-6
    patience: 100
    step_size:
    - 250
    - 0.01
    type: linear
    verbose: false
trial_name: phill_inter
